import { NgModule } from '@angular/core';
import {	MatAutocompleteModule,
					MatBadgeModule,
					MatButtonModule, 
					MatCardModule, 
					MatCheckboxModule,
					MatChipsModule,
					MatDatepickerModule,
					MatDialogModule,
					MatExpansionModule,
					MatGridListModule,
					MatIconModule,
					MatInputModule,
					MatListModule,
					MatMenuModule,
					MatNativeDateModule,
					MatProgressSpinnerModule,
					MatRadioModule,
					MatTableModule,
					MatToolbarModule,
					MatTooltipModule,					
					MatSelectModule,
					MatPaginatorModule,
					MatSlideToggleModule,
			
					MatBottomSheetModule,

					MatButtonToggleModule,

					MatDividerModule,
					MatProgressBarModule,
					MatRippleModule,
					MatSidenavModule,
					MatSliderModule,

					MatSnackBarModule,
					MatSortModule,
					MatStepperModule,
					MatTabsModule,
					MatTreeModule,

				
				
				
				} from '@angular/material';

@NgModule({
  imports: [
  	MatAutocompleteModule,
  	MatBadgeModule,
		MatButtonModule, 
		MatCardModule, 
		MatCheckboxModule, 
		MatChipsModule,
		MatDatepickerModule,
		MatDialogModule,
		MatExpansionModule,
		MatGridListModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatMenuModule,
		MatNativeDateModule,
		MatProgressSpinnerModule,
		MatRadioModule,
		MatTableModule,
		MatToolbarModule,
		MatTooltipModule,
		MatSelectModule,
		MatSlideToggleModule,
		MatAutocompleteModule,
		MatBadgeModule,
		MatButtonModule,
		MatCardModule,
		MatCheckboxModule,
		MatChipsModule,
		MatDatepickerModule,
		MatDialogModule,
		MatExpansionModule,
		MatGridListModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatMenuModule,
		MatNativeDateModule,
		MatProgressSpinnerModule,
		MatRadioModule,
		MatSelectModule,
		MatSlideToggleModule,
		MatTableModule,
		MatToolbarModule,
		MatTooltipModule,
		MatPaginatorModule,
		MatBottomSheetModule,

		MatButtonToggleModule,

		MatDividerModule,
		MatProgressBarModule,
		MatRippleModule,
		MatSidenavModule,
		MatSliderModule,

		MatSnackBarModule,
		MatSortModule,
		MatStepperModule,
		MatTabsModule,
		MatTreeModule,
  ],
  exports: [
  	MatAutocompleteModule,
  	MatBadgeModule,
  	MatButtonModule, 
		MatCardModule, 
		MatCheckboxModule, 
		MatChipsModule,
		MatDatepickerModule,
		MatDialogModule,
		MatExpansionModule,
		MatGridListModule,
		MatIconModule,
		MatInputModule,
		MatListModule,
		MatMenuModule,
		MatNativeDateModule,
		MatProgressSpinnerModule,
		MatRadioModule,
		MatTableModule,
		MatToolbarModule,
		MatTooltipModule,
		MatSelectModule,
		MatSlideToggleModule,

    MatAutocompleteModule,
    MatBadgeModule,
    MatButtonModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatTableModule,
    MatToolbarModule,
	MatTooltipModule,
	MatButtonToggleModule,

	MatDividerModule,
	MatProgressBarModule,
	MatRippleModule,
	MatSidenavModule,
	MatSliderModule,

	MatSnackBarModule,
	MatSortModule,
	MatStepperModule,
	MatTabsModule,
	MatTreeModule,
	MatPaginatorModule
	],
  declarations: [],
})
export class AngularMaterialModule { }